### ISSUE TITLE
Exception Error when i use sleep in my filter 

### ISSUE THREAD

**Issue by DBARUNNER** [logstash-plugins/logstash-filter-sleep#5]
my filter is 
filter {
    sleep 
     {
       time    => "5"
       every   => "10"
    }
}

when i run my logstash wiht config file it output me an error, #exception in filterworker stop processing new events, comparison of fixnum with string

**Comment by jordansissel** [comment]
A PR for this here: https://github.com/logstash-plugins/logstash-filter-sleep/pull/6

**Comment by jordansissel** [comment]
#6 is merged.
